// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cloud/doublecloud/public-api/doublecloud/transfer/v1/endpoint/airbyte/amazon_ads_source.proto

package endpoint_airbyte

import (
	fmt "fmt"
	"google.golang.org/protobuf/proto"
	math "math"

	schema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// AmazonAdsSource_TF struct with tfsdk field AmazonAdsSource AmazonAdsSource
type AmazonAdsSource_TF struct {
	ClientId     types.String  `tfsdk:"client_id",json:"client_id"`
	ClientSecret types.String  `tfsdk:"client_secret",json:"client_secret"`
	Scope        types.String  `tfsdk:"scope",json:"scope"`
	RefreshToken types.String  `tfsdk:"refresh_token",json:"refresh_token"`
	StartDate    types.String  `tfsdk:"start_date",json:"start_date"`
	Region       types.String  `tfsdk:"region",json:"region"`
	Profiles     types.Float64 `tfsdk:"profiles",json:"profiles"`
}

func GenTFSchemaAmazonAdsSource() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
		"client_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"client_secret": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"profiles": schema.Float64Attribute{
			Description: "",
			Optional:    true,
		},
		"refresh_token": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"region": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"scope": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"start_date": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
