// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cloud/doublecloud/public-api/doublecloud/transfer/v1/endpoint/airbyte/aws_cloud_trail_source.proto

package endpoint_airbyte

import (
	fmt "fmt"
	"google.golang.org/protobuf/proto"
	math "math"

	schema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// AWSCloudTrailSource_TF struct with tfsdk field AWSCloudTrailSource AWSCloudTrailSource
type AWSCloudTrailSource_TF struct {
	AwsKeyId      types.String `tfsdk:"aws_key_id",json:"aws_key_id"`
	AwsSecretKey  types.String `tfsdk:"aws_secret_key",json:"aws_secret_key"`
	AwsRegionName types.String `tfsdk:"aws_region_name",json:"aws_region_name"`
	StartDate     types.String `tfsdk:"start_date",json:"start_date"`
}

func GenTFSchemaAWSCloudTrailSource() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
		"aws_key_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"aws_region_name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"aws_secret_key": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"start_date": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
