// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cloud/doublecloud/public-api/doublecloud/transfer/v1/endpoint/airbyte/bigquery_source.proto

package endpoint_airbyte

import (
	fmt "fmt"
	"google.golang.org/protobuf/proto"
	math "math"

	schema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// BigQuerySource_TF struct with tfsdk field BigQuerySource BigQuerySource
type BigQuerySource_TF struct {
	ProjectId       types.String `tfsdk:"project_id",json:"project_id"`
	DatasetId       types.String `tfsdk:"dataset_id",json:"dataset_id"`
	CredentialsJson types.String `tfsdk:"credentials_json",json:"credentials_json"`
}

func GenTFSchemaBigQuerySource() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
		"credentials_json": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"dataset_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"project_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
