// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cloud/doublecloud/public-api/doublecloud/transfer/v1/endpoint/airbyte/facebook_marketing_source.proto

package endpoint_airbyte

import (
	fmt "fmt"
	"google.golang.org/protobuf/proto"
	math "math"

	schema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// InsightConfig_TF struct with tfsdk field InsightConfig FacebookMarketingSource.custom_insights
type InsightConfig_TF struct {
	Name             types.String `tfsdk:"name",json:"name"`
	Fields           types.Int64  `tfsdk:"fields",json:"fields"`
	Breakdowns       types.Int64  `tfsdk:"breakdowns",json:"breakdowns"`
	ActionBreakdowns types.Int64  `tfsdk:"action_breakdowns",json:"action_breakdowns"`
}

func GenTFSchemaInsightConfig() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
		"action_breakdowns": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"breakdowns": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"fields": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"name": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}

// FacebookMarketingSource_TF struct with tfsdk field FacebookMarketingSource FacebookMarketingSource
type FacebookMarketingSource_TF struct {
	StartDate            types.String      `tfsdk:"start_date",json:"start_date"`
	AccountId            types.String      `tfsdk:"account_id",json:"account_id"`
	EndDate              types.String      `tfsdk:"end_date",json:"end_date"`
	AccessToken          types.String      `tfsdk:"access_token",json:"access_token"`
	IncludeDeleted       types.Bool        `tfsdk:"include_deleted",json:"include_deleted"`
	FetchThumbnailImages types.Bool        `tfsdk:"fetch_thumbnail_images",json:"fetch_thumbnail_images"`
	CustomInsights       *InsightConfig_TF `tfsdk:"custom_insights",json:"custom_insights"`
}

func GenTFSchemaFacebookMarketingSource() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
		"access_token": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"account_id": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"custom_insights": schema.SingleNestedAttribute{
			Attributes:  GenTFSchemaInsightConfig().Attributes,
			Description: "",
			Optional:    true,
		},
		"end_date": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"fetch_thumbnail_images": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"include_deleted": schema.BoolAttribute{
			Description: "",
			Optional:    true,
		},
		"start_date": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
