// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cloud/doublecloud/public-api/doublecloud/transfer/v1/endpoint/airbyte/redshift_source.proto

package endpoint_airbyte

import (
	fmt "fmt"
	"google.golang.org/protobuf/proto"
	math "math"

	schema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// RedshiftSource_TF struct with tfsdk field RedshiftSource RedshiftSource
type RedshiftSource_TF struct {
	Host     types.String `tfsdk:"host",json:"host"`
	Port     types.Int64  `tfsdk:"port",json:"port"`
	Database types.String `tfsdk:"database",json:"database"`
	Schemas  types.String `tfsdk:"schemas",json:"schemas"`
	Username types.String `tfsdk:"username",json:"username"`
	Password types.String `tfsdk:"password",json:"password"`
}

func GenTFSchemaRedshiftSource() schema.SingleNestedBlock {
	return schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
		"database": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"host": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"password": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"port": schema.Int64Attribute{
			Description: "",
			Optional:    true,
		},
		"schemas": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
		"username": schema.StringAttribute{
			Description: "",
			Optional:    true,
		},
	}}
}
